### ISSUE TITLE
atlarge.ewi.tudelft.nl server down

### ISSUE THREAD

**Issue by sampollard** [ldbc/ldbc_graphalytics#110]
I am unable to access the graph datasets. Is there any other place I can access them?

**Comment by thegeman** [comment]
We are working on bringing the server back online, but it's taking longer than anticipated. We are also looking into alternatives like Amazon S3, but we would need to use the "requester pays" model to cover the costs.

**Comment by thegeman** [comment]
The server is up again, so I will close this issue.
