### ISSUE TITLE
Graphs not available to donwload

### ISSUE THREAD

**Issue by narayanan2004** [ldbc/ldbc_graphalytics#111]
The prescribed path - http://atlarge.ewi.tudelft.nl/graphalytics/ in README to download the graphs returns a 404 error. Please change the link to point to the correct location.

**Comment by thegeman** [comment]
Thank you for pointing out this issue. It appears that the download page is not served correctly via HTTP. For now please use [https://atlarge.ewi.tudelft.nl/graphalytics/](https://atlarge.ewi.tudelft.nl/graphalytics/) instead.

**Comment by mihaic** [comment]
There is a redirect to HTTPS now. You can close this issue.
