### ISSUE TITLE
Add an overall validation indicator

### ISSUE THREAD

**Issue by mihaic** [ldbc/ldbc_graphalytics#119]
As far as I can tell, the only way to determine if there were validation failures in a Graphalytics run is to examine each benchmark validation result. It would be useful to have an indication that the validation succeeded overall, e.g., "Validation successful for all benchmarks" printed at the end of the command line output and at the top of the experimental tab in the HTML report.

**Comment by wlngai** [comment]
The benchmark suite now indicates 7 types of failures (See more details our specification Section 3.3.4 https://github.com/ldbc/ldbc_graphalytics_docs). If failures, e.g. validation failure (VAT) occurs, the command line output will report the failures in each benchmark run, and will also provide an overview of all benchmark runs at the end.
