### ISSUE TITLE
Unmanaged maven dependencies.

### ISSUE THREAD

**Issue by wlngai** [ldbc/ldbc_graphalytics#144]
Dependencies, such as the graphalytics-core, Granula modules, and platform jars with instrumentation code, are not easily accessible from the central maven repository. Instead, users need to build these dependencies themselves.

We cannot publish unofficial project artifacts to the maven central repo, but we should have a private maven repository for the convenience of our collaborators.

**Comment by wlngai** [comment]
The Graphalytics maven repository has been set up in `http://graphalytics.site/maven`. However, the repository still needs to be migrated to its final destination `http://maven.graphalytics.org`.

**Comment by Luca-Virgilio** [comment]
I found an implementation driver for the platform Neo4j, but I need old version (0.3) of graphalytics-core that is not avaible in the new repository or in maven repository. What shall I do?

**Comment by szarnyasg** [comment]
There is a Maven repository hosted using GitHub Pages:

- https://github.com/ldbc/ldbc_graphalytics/issues/210#issuecomment-980002987
- https://github.com/ldbc/graphalytics-mvn
- https://ldbcouncil.org/graphalytics-mvn/
