### ISSUE TITLE
Where to find benchmark datasets ?

### ISSUE THREAD

**Issue by niusj** [ldbc/ldbc_graphalytics#161]
When I tried to benchmark powergraph platform with Graphalytics, I saw graph links in the directory: config-template/graphs/*.properties. Shall I just download them as input datasets ? And what about validation datasets ? Also, where are the input datasets and validation datasets for the test example-directed and example-undirected ? Thanks !

**Comment by thegeman** [comment]
Hi @niusj,

All datasets, including the examples, are available on our website: http://graphalytics.org/site/dist/index.html?p=dataset. For every dataset we provide a `<graph-name>.zip` file containing the graph data (`<graph-name>.e` and `<graph-name>.v`) and in most cases validation output for each algorithm (`<graph-name>-<algortihm>`). Just download the graphs you are interested in running the benchmark on.

Let me know if you encounter any problems running the benchmark.

**Comment by niusj** [comment]
Thank you so much !
