### ISSUE TITLE
Implementation issues

### ISSUE THREAD

**Issue by asifbanka** [ldbc/ldbc_graphalytics#164]
Dear team,

I find this an extremely exciting project and look forward to contribute.

Being a novice I am facing issues at very early part of implementation. I have cloned the graphanalytics and now I m stuck which direction to take. I tried to clone graphanalytics_refrence its throwing an error mentioning it needs username and password. I m also interested to look how can granula and datagen be installed. 

Can you please redirect me to some reference manual that could be followed to take the implementation further.

**Comment by amusaafir** [comment]
Hello @asifbanka,

Thank you for the interest!

We're currently in the final stages of releasing the new Graphalytics website and we're planning to improve the documentation later this month as well.

For now, please follow the following guides to perform a benchmark: 

1) [Building the software](https://github.com/ldbc/ldbc_graphalytics/wiki/Documentation%3A-Software-Build)

2) [Running the benchmark](https://github.com/ldbc/ldbc_graphalytics/wiki/Manual%3A-Running-Benchmark)

_Please keep in mind that the links to the prebuilt drivers are currently not available and these have to be built yourself (this is also explained in the documentation)._

A rough guideline:

After you've cloned the Graphalytics project (make sure you clone it from [this repository](https://github.com/ldbc/ldbc_graphalytics.git)), you will need to run `mvn clean install` once in the root of the directory. This should install Graphalytics locally into your Maven repository.

Similarly, to install Granula: `mvn clean install -Pgranula`.

First, you'll need to download the [graph datasets](http://graphalytics.org/site/dist/index.html?p=dataset). For now, I recommend downloading only `example-directed` and `example-undirected` as these are used to perform a `test` benchmark (which should be performed quickly regardless of the system). Download and unzip these in a single folder.

After this, you can clone a platform specific driver (e.g., [GraphMat](https://github.com/atlarge-research/graphalytics-platforms-graphmat) which can be found [here](https://github.com/atlarge-research/) among other drivers indicated by `graphalytics-platform-*`). 

While each driver has its own dependencies and installation steps, the general procedure that needs to be conducted is roughly the same all of them and is described in the repository of the driver. Essentially, you will only have to modify the configuration files in the platform specific drivers according to your needs. 

Important properties that you will need to modify in the driver (note there may be others so please consult the platform specific driver documentation) :

- `config/platform.properties` - refer to the root directory of the graph processing system in the `platform.{{platformName}}.home` property.
- `config/benchmark.properties` - make sure that *only* the required type of benchmark is included (in case of a `test` benchmark, this would be `include = benchmarks/test.properties`). Furthermore, make sure to refer to your datasets folder in the `graphs.root-directory` property.
- `config/granula.properties` - to enable Granula, set `benchmark.run.granula.enabled` to `true`.

Should you need any further information please let us know!

**Comment by asifbanka** [comment]
I appreciate your timely response and for now will follow your instruction. Will look forward for further updates.

Thanks again

**Comment by asifbanka** [comment]
If Hadoop and spark are already installed, do we need to re-run the package as mvn installation downloads a fresh copy of Hadoop. Should I keep the default settings as modified by graphanalytics-platform or I can have my version of Hadoop as default

**Comment by asifbanka** [comment]
After I clone giraph, mvn installation is thowing an error

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:27 h
[INFO] Finished at: 2018-04-03T17:00:48+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project graphalytics-platforms-giraph: Could not resolve dependencies for project science.atlarge.graphalytics:graphalytics-platforms-giraph:jar:0.2-SNAPSHOT: Could not transfer artifact org.apache.giraph:giraph-core-granula:jar:1.2.0-hadoop2 from/to graphalytics (http://graphalytics.site/maven): Checksum validation failed, no checksums available -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

Is this due to conflict of Hadoop settings

**Comment by amusaafir** [comment]
Regarding the error you receive: after you have cloned the [Giraph driver](https://github.com/atlarge-research/graphalytics-platforms-giraph), you will need to run `mvn clean package` in the root of the directory of the driver (rather than `mvn clean install`). This should create the `tar.gz` file. This would use the `ldbc_graphalytics` dependency which you should have installed locally on your machine, i.e.: you first have to run `mvn clean install` on the [ldbc_graphalytics](https://github.com/ldbc/ldbc_graphalytics) project. 

Note that your existing installation (and configuration) of Hadoop and Spark should not be affected when packaging the drivers. After running `mvn clean package` on the root directory of the driver (and subsequently after you have extracted the tar file), you should be able to modify the configuration files *of the driver alone* and refer to your local Hadoop installation.

**Comment by asifbanka** [comment]
When I try to mvn clean package in usr/local/Cellar/graphanalytics/graphalytics-platforms-graphx I get the following error

[ERROR] error: error while loading package, Missing dependency 'object java.lang.Object in compiler mirror', required by /Users/asifalibanka/.m2/repository/org/scala-lang/scala-library/2.10.4/scala-library-2.10.4.jar(scala/package.class)
[ERROR] error: error while loading package, Missing dependency 'object java.lang.Object in compiler mirror', required by /Users/asifalibanka/.m2/repository/org/scala-lang/scala-library/2.10.4/scala-library-2.10.4.jar(scala/runtime/package.class)
[ERROR] error: scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.
[ERROR] 	at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:16)
[ERROR] 	at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:17)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:48)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:40)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:40)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:61)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getClassByName(Mirrors.scala:99)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getRequiredClass(Mirrors.scala:102)
[ERROR] 	at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass$lzycompute(Definitions.scala:264)
[ERROR] 	at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass(Definitions.scala:264)
[ERROR] 	at scala.reflect.internal.Definitions$DefinitionsClass.AnyRefClass$lzycompute(Definitions.scala:263)
[ERROR] 	at scala.reflect.internal.Definitions$DefinitionsClass.AnyRefClass(Definitions.scala:263)
[ERROR] 	at scala.reflect.internal.Definitions$DefinitionsClass.specialPolyClass(Definitions.scala:1120)
[ERROR] 	at scala.reflect.internal.Definitions$DefinitionsClass.RepeatedParamClass$lzycompute(Definitions.scala:407)
[ERROR] 	at scala.reflect.internal.Definitions$DefinitionsClass.RepeatedParamClass(Definitions.scala:407)
[ERROR] 	at scala.reflect.internal.Definitions$DefinitionsClass.syntheticCoreClasses$lzycompute(Definitions.scala:1154)
[ERROR] 	at scala.reflect.internal.Definitions$DefinitionsClass.syntheticCoreClasses(Definitions.scala:1152)
[ERROR] 	at scala.reflect.internal.Definitions$DefinitionsClass.symbolsNotPresentInBytecode$lzycompute(Definitions.scala:1196)
[ERROR] 	at scala.reflect.internal.Definitions$DefinitionsClass.symbolsNotPresentInBytecode(Definitions.scala:1196)
[ERROR] 	at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1261)
[ERROR] 	at scala.tools.nsc.Global$Run.<init>(Global.scala:1290)
[ERROR] 	at scala.tools.nsc.Driver.doCompile(Driver.scala:32)
[ERROR] 	at scala.tools.nsc.Main$.doCompile(Main.scala:79)
[ERROR] 	at scala.tools.nsc.Driver.process(Driver.scala:54)
[ERROR] 	at scala.tools.nsc.Driver.main(Driver.scala:67)
[ERROR] 	at scala.tools.nsc.Main.main(Main.scala)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[ERROR] 	at scala_maven_executions.MainHelper.runMain(MainHelper.java:164)
[ERROR] 	at scala_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
[ERROR] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 27:25 min
[INFO] Finished at: 2018-04-04T15:55:58+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.0:compile (default) on project graphalytics-platforms-graphx: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException


When I try to look for giraph package it asks for a username and password. I tried to access http://graphalytics.site/dist/

**Comment by asifbanka** [comment]
if I run mvn clean package in usr/local/Cellar/graphanalytics/graphalytics-platforms-giraph

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.221 s
[INFO] Finished at: 2018-04-04T16:06:39+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project graphalytics-platforms-giraph: There are test failures.
[ERROR] 
[ERROR] Please refer to /usr/local/Cellar/ldbc_graphalytics/graphalytics-platforms-giraph/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by asifbanka** [comment]
Thanks!

Done with installation of drivers. Installed giraph, graphx, powergraph and graphmat.
Now I look forward to have some hands-on on these. 
Will need your guidance to take my work further.

How do I proceed next after having drivers installed
