### ISSUE TITLE
PropertyList is empty

### ISSUE THREAD

**Issue by nizhegorodets** [ldbc/ldbc_graphalytics#172]
hello!

i'm trying run benchmark with "custom.properties"

```
# Properties file for defining the benchmark type

# Name and Type of the benchmark run
benchmark.name = Custom Benchmark
benchmark.type = custom

# Select a subset of the graphs
benchmark.custom.graphs = datagen-7_6-fb

# Select a subset of the algorithms
benchmark.custom.algorithms = bfs

# Specify the duration before a benchmark run is timed out.
benchmark.custom.timeout = 3600

# Specify if output and validation is required.
benchmark.custom.output-required = true
benchmark.custom.validation-required = true

benchmark.custom.repetitions = 1
```

In preprocessing phase i see 

> Generating edge file for graph "datagen-7_6-fb" at "/media/dmitry/2bef494f-a852-46e7-bea9-1d40b08306aa/datasets/cache/datagen-7_6-fb.e" with edge properties PropertyList{properties=[]}.

and PropertyList is empty. I want to add "weight" to generated edge file.
How can I do it?

Thanks!

**Comment by thegeman** [comment]
Hi @nizhegorodets,

The `datagen-7_6-fb` graph has edge weights by default, so they should be included in the `datagen-7_6-fb.e` file you downloaded from our website. However, the BFS algorithm you selected for your custom benchmark does not use edge weights. If you want to use the weighted graph, you could run SSSP or implement some of your own algorithms.

To clarify what the log statement that you highlighted means: Graphalytics creates a copy of the graph without edge weights in the preprocessing phase. This allows platforms that do not support edge weights to parse the graph without any properties and run BFS (and other algorithms that do not use weights).

Hope this helps.

**Comment by nizhegorodets** [comment]
> Hi @nizhegorodets,
> 
> The `datagen-7_6-fb` graph has edge weights by default, so they should be included in the `datagen-7_6-fb.e` file you downloaded from our website. However, the BFS algorithm you selected for your custom benchmark does not use edge weights. If you want to use the weighted graph, you could run SSSP or implement some of your own algorithms.
> 
> To clarify what the log statement that you highlighted means: Graphalytics creates a copy of the graph without edge weights in the preprocessing phase. This allows platforms that do not support edge weights to parse the graph without any properties and run BFS (and other algorithms that do not use weights).
> 
> Hope this helps.

Thanks! It very useful for me
