### ISSUE TITLE
Template header points to 404

### ISSUE THREAD

**Issue by szarnyasg** [ldbc/ldbc_graphalytics#177]
The archetype points to http://www.pds.ewi.tudelft.nl/~mihai/copyright-notice-template as the header template, which is a 404.

https://github.com/ldbc/ldbc_graphalytics/blob/98248e1f3affbd31477066bd06c4cc5f147b02e2/graphalytics-platforms-default-archetype/src/main/resources/archetype-resources/pom.xml#L175

**Comment by amusaafir** [comment]
Thanks for the reminder! https://github.com/ldbc/ldbc_graphalytics/commit/84bac6b873753d02354c3e39920f7e5758c7c113
