### ISSUE TITLE
How to link the platform driver to the benchmark driver

### ISSUE THREAD

**Issue by whatsthecraic** [ldbc/ldbc_graphalytics#179]
Dear folks,

I'm trying to follow the instructions from https://github.com/ldbc/ldbc_graphalytics/wiki/Manual%3A-Running-Benchmark , still I stuck on how to link the benchmark with a platform driver. Right now I've three folders:
```
/benchmarks # with the benchmark driver
/driver-graphmat # with the graphmat driver
/GraphMat/ # with graphmat
```
/driver-graphmat/config/platform.properties has a property named platform.graphmat.home to set the location of graphmat, the question now is how to link /driver-graphmat to the benchmark driver?

Thanks,
Dean

**Comment by amusaafir** [comment]
Hi @whatsthecraic . The `platform.graphmat.home` property inside the `platform.properties` file should refer to the root directory of GraphMat. That's the only thing required to link the driver to the platform.

**Comment by whatsthecraic** [comment]
AFAIU there is a separate program with a logic to handle the benchmark suite (this repository) and then there is a connector for each system to evaluate (the platform driver). When downloading the graphalytics program there is no system configured, i.e. there is no config/platform.properties or so. I think the artifacts from the two repositories, the graphalytics and the specific connector, need to be merged somehow in the same folder. I'm giving a try with the graphmat connector. So far I've managed to compile the C++ source code, but now I'm stuck on how  to link the graphalytics benchmark with the graphmat java driver.  I've created a few symlinks to compile-benchmarks.sh , prepare-benchmarks.sh and bin/standards (the C++ programs from the graphmat driver) inside the graphalytics-benchmark suite. Still when executing the ./run-benchmarks.sh the script fails with 
```
ls: cannot access 'lib/graphalytics-*default*.jar': No such file or directory
The prepare-benchmark.sh script must set variable $LIBRARY_JAR
```
I assumed that  `mvn install` should have created these .jar packages. Anyway I'm not that knowledgeable of the java ecosystem and I might need a little help to continue now. 

Thanks,
Dean

**Comment by whatsthecraic** [comment]
oky, I think I've made a little bit of progress. I finally realised that the platform driver already creates an archive, graphalytics-1.0.0-graphmat-0.2-SNAPSHOT-bin.tar.gz, with both the benchmark suite & the connector, already merged. I guess in general there is no need to fiddle with this ldbc repo directly, only the platform driver is enough to create that package, right? The other point is that the script must be executed from the the top directory of the extracted archive, e.g.  ./bin/sh/run-benchmark.sh

Now, doing that issues the following exception:
```
07:39 [INFO ] Initializing Benchmark Suite.
07:39 [INFO ] Parsing GraphMat configuration file.
07:39 [INFO ] Loading Benchmark...
07:39 [INFO ] Imported 0 graph(s): [].
07:39 [INFO ] Failed to import 30 graph(s): [dota-league, com-friendster, twitter_mpi, graph500-22, graph500-23, graph500-24, graph500-25, graph500-26, datagen-7_5-fb, datagen-7_6-fb, datagen-7_7-zf, datagen-7_8-zf, datagen-7_9-fb, datagen-8_0-fb, datagen-8_1-fb, datagen-8_2-zf, datagen-8_3-zf, datagen-8_4-fb, datagen-8_5-fb, datagen-8_6-fb, datagen-8_7-zf, datagen-8_8-zf, datagen-8_9-fb, datagen-9_0-fb, datagen-9_1-fb, datagen-9_2-zf, datagen-9_3-zf, datagen-9_4-fb, example-directed, example-undirected].
Exception in thread "main" java.lang.IllegalStateException: Benchmark failed: graph info does not match expectation: dota-league
	at science.atlarge.graphalytics.domain.benchmark.StandardBenchmark.setupExperiments(StandardBenchmark.java:108)
	at science.atlarge.graphalytics.domain.benchmark.StandardBenchmark.setup(StandardBenchmark.java:64)
	at science.atlarge.graphalytics.execution.BenchmarkLoader.parse(BenchmarkLoader.java:114)
	at science.atlarge.graphalytics.BenchmarkSuite.main(BenchmarkSuite.java:72)
```

which further brings into question how the suite knows which graphs to use and where is the validation set? Is it expected to load all graphs inside the directory set in `graphs.root-directory' inside benchmark properties? That is
```
# ls /linux/workspace/graphalytics/datasets/
datagen-7_5-fb.zip  datagen-7_6-fb.zip  datagen-7_7-zf.zip  datagen-7_8-zf.zip  datagen-7_9-fb.zip  dota-league.zip  example-directed.zip  example-undirected.zip  graph500-22.zip  s.txt
```

Thanks,
Dean

**Comment by amusaafir** [comment]
You'll need to extract the dataset zip files in your `/linux/workspace/graphalytics/datasets/` directory. The path of this directory can then be set as value in both the `graphs.root-directory` and `graphs.validation-directory` properties, inside the `benchmark.properties` file.

**Comment by whatsthecraic** [comment]
Ok, a bit of more progress: 
```
10:49 [INFO ] Initializing Benchmark Suite.
10:49 [INFO ] Parsing GraphMat configuration file.
10:49 [INFO ] Loading Benchmark...
10:49 [INFO ] Imported 1 graph(s): [dota-league].
10:49 [INFO ] Failed to import 29 graph(s): [com-friendster, twitter_mpi, graph500-22, graph500-23, graph500-24, graph500-25, graph500-26, datagen-7_5-fb, datagen-7_6-fb, datagen-7_7-zf, datagen-7_8-zf, datagen-7_9-fb, datagen-8_0-fb, datagen-8_1-fb, datagen-8_2-zf, datagen-8_3-zf, datagen-8_4-fb, datagen-8_5-fb, datagen-8_6-fb, datagen-8_7-zf, datagen-8_8-zf, datagen-8_9-fb, datagen-9_0-fb, datagen-9_1-fb, datagen-9_2-zf, datagen-9_3-zf, datagen-9_4-fb, example-directed, example-undirected].
Exception in thread "main" java.lang.NullPointerException
	at science.atlarge.graphalytics.domain.benchmark.Benchmark.verifyGraphInfo(Benchmark.java:178)
	at science.atlarge.graphalytics.domain.benchmark.TestBenchmark.setupExperiments(TestBenchmark.java:108)
	at science.atlarge.graphalytics.domain.benchmark.TestBenchmark.setup(TestBenchmark.java:62)
	at science.atlarge.graphalytics.execution.BenchmarkLoader.parse(BenchmarkLoader.java:107)
	at science.atlarge.graphalytics.BenchmarkSuite.main(BenchmarkSuite.java:72)
```
after having extracted a single dataset:
``` 
# ls /home/dean/workspace/graphalytics/datasets/extracted/
dota-league-BFS   dota-league.e    dota-league-PR          dota-league-SSSP  dota-league-WCC
dota-league-CDLP  dota-league-LCC  dota-league.properties  dota-league.v
```

is it supposed to run all datasets that it finds in the directory?

**Comment by whatsthecraic** [comment]
Ok I assume it follows the list set in graphs.properties. Still, restricting to only the dota graph:
```
10:57 [INFO ] Initializing Benchmark Suite.
10:57 [INFO ] Parsing GraphMat configuration file.
10:57 [INFO ] Loading Benchmark...
10:57 [INFO ] Imported 1 graph(s): [dota-league].
Exception in thread "main" java.lang.NullPointerException
	at science.atlarge.graphalytics.domain.benchmark.Benchmark.verifyGraphInfo(Benchmark.java:178)
	at science.atlarge.graphalytics.domain.benchmark.TestBenchmark.setupExperiments(TestBenchmark.java:108)
	at science.atlarge.graphalytics.domain.benchmark.TestBenchmark.setup(TestBenchmark.java:62)
	at science.atlarge.graphalytics.execution.BenchmarkLoader.parse(BenchmarkLoader.java:107)
	at science.atlarge.graphalytics.BenchmarkSuite.main(BenchmarkSuite.java:72)
```

**Comment by amusaafir** [comment]
Can you check what type of benchmark you are running (test/standard/custom)? You can do that by opening `benchmark.properties` and looking at which benchmark type is included above. Make sure to include only one type of benchmark.

In any case, I would only include the custom benchmark type and comment out the includes for test and standard.
Then, in `config/benchmark/custom.properties` you are able to select which datasets you would like to include (in the `benchmark.custom.graphs` property). E.g. : `benchmark.custom.graphs = graph500-25, datagen-8_5-fb` 

Similarly for the algorithms, e.g.: `benchmark.custom.algorithms = bfs, pr` 

These datasets should be available in `/home/dean/workspace/graphalytics/datasets/extracted/`

**Comment by whatsthecraic** [comment]
More progress, see log https://pastebin.com/EaZbPyCE

**Comment by amusaafir** [comment]
I don't think your cluster has Slurm installed, is this correct? In that case, you can use [this](https://github.com/amusaafir/graphalytics-platforms-graphmat/blob/master/config-template/platform.properties) platform configuration (modify it accordingly to your needs - specifically the `platform.graphmat.enable-slurm`, `platform.graphmat.num_local_processes` and `platform.graphmat.hosts` properties).

**Comment by whatsthecraic** [comment]
oky, I've managed to install slurm, see log: https://pastebin.com/sECUcSsy
configuration: https://pastebin.com/WDRLfguT

Is mpiexec.hydra is another prerequisite? :fearful:

**Comment by whatsthecraic** [comment]
ok, replacing mpiexec.hydra with mpiexec did the trick for me, https://pastebin.com/WM4SF1D7
still, I think the config you gave me should have disabled running both slurm and mpi, right?

**Comment by amusaafir** [comment]
Replacing it with mpiexec/mpirun should indeed also work. However, in hindsight, the properties file that I gave should only work if you had used the driver which was downloaded using the Graphalytics installer (essentially the modified driver used for the installer that contains the custom platform properties file).

If the driver was cloned from the default Graphmat repository and the modified platform properties file was used, it wouldn't disable Slurm.

I will update the default driver repository and add some fixes to the installer to make these steps more clear.

**Comment by whatsthecraic** [comment]
Hi there,
in ref. to the configuration posted here: https://github.com/amusaafir/graphalytics-platforms-graphmat/blob/master/config-template/platform.properties
I want to execute Graphmat on a single machine with 24 cores and 48 threads, possibly without having to install slurm. I'm trying the following tentative configuration:
```
platform.graphmat.num-threads = 48
platform.graphmat.enable-slurm = False
platform.graphmat.num-machines = 1
...
platform.graphmat.hosts = localhost
platform.graphmat.num_local_processes = 1
```
Is this configuration correct? Can you elaborate what the parameters platform.graphmat.hosts and platform.graphmat.num_local_processes do ?

Thanks,
Dean

**Comment by whatsthecraic** [comment]
I'm asking that as the graphmat implementation completed LCC in 23 minutes on the small `dota-league' graph, while all the other algorithms on the same graph were able to finish in a few tens of seconds. Is there any known issue for this implementation?

**Comment by amusaafir** [comment]
Hi,

The `hosts` property should contain a list of hosts on which to run GraphMat on (the number of hosts specified should be equivalent to `num-machines`). The `num_local_processes` property specifies the number of processes (this will be essentially passed using `--np`) . Each process can run on a separate core, but make sure that you are not [oversubscribing](https://www.open-mpi.org/faq/?category=running#oversubscribing). The config you've posted looks fine, although you could try setting this property to 12 or 24 and see whether you get a performance boost. 

Regarding dota-league and running local clustering coefficient: dota-league is quite a dense graph. I've observed similar numbers (although not to the same extent) as you for Graphmat and also when using PowerGraph.

**Comment by szarnyasg** [comment]
> I'm asking that as the graphmat implementation completed LCC in 23 minutes on the small `dota-league' graph, while all the other algorithms on the same graph were able to finish in a few tens of seconds. Is there any known issue for this implementation?

Regarding the complexity of LCC, Julian Shun et al.'s paper ["Theoretically Efficient Parallel Graph Algorithms Can Be Fast and Scalable"](https://arxiv.org/abs/1805.05208) is a good pointer. This discusses that triangle count (which is essentially a sub-problem of LCC) is significantly more expensive than most common graph algorithms.
