### ISSUE TITLE
Are all but one graphs undirected?

### ISSUE THREAD

**Issue by whatsthecraic** [ldbc/ldbc_graphalytics#180]
Dears folks, 
in the datasets page, as most graphs are created from either  graph500 or the ldbc datagen, they are undirected. The only directed graph is twitter, but it's labelled with "Incorrect Vertex Count". Can you elaborate whether more directed graphs will be included and what are the consequences of using the twitter graph in benchmark?

**Comment by amusaafir** [comment]
Correct - the bulk of the datasets are undirected. There is currently no plan to add more directed graphs. However, you can always use your [own](https://github.com/ldbc/ldbc_graphalytics/wiki/Manual%3A-Using-your-own-data-sets) directed datasets. 
The Twitter dataset should work fine (including validation). IIRC, the number of vertices specified in the properties file is different than the actual number (52,579,678). I'll add this explicitly on the site and will update the actual properties file once I have access to change this.

**Comment by szarnyasg** [comment]
Here's a "colour-coded" spreadsheet with the datasets: https://docs.google.com/spreadsheets/d/e/2PACX-1vTuNlJDe521a21Conz5IjPiDwVvd0Rrd_WwJ7aUkszABDi9lvIwezesvzn2S2XblELa7wUAtisbu-jF/pubhtml
