### ISSUE TITLE
Error message when the process stops on its own

### ISSUE THREAD

**Issue by szarnyasg** [ldbc/ldbc_graphalytics#183]
Some implementations, e.g. SuiteSparse:GraphBLAS exit upon finishing. Therefore, the framework throws an error stating that it couldn't kill the process:

```console
07:38 [WARN ] Terminating process 13674 focibly.
07:38 [WARN ] Executing command "kill -9 13674"
07:38 [ERROR] Failed to kill runner process.
```

This might be confusing, especially for newcomers. It's definitely annoying for regulars as well :-).
Is there a way to turn this off?

**Comment by amusaafir** [comment]
This is indeed confusing - #184 should fix this. Please reinstall Graphalytics and your driver accordingly.
