### ISSUE TITLE
How to repeat the execution times when using graphmat?

### ISSUE THREAD

**Issue by whatsthecraic** [ldbc/ldbc_graphalytics#191]
I'm comparing the processing times obtained while executing graphmat against a simple sequential baseline with the algorithms implemented following the pseudo code in the ref. spec. Problem is the processing times of graphmat are not what we were expecting. In the dota-league and graph500-[22,26] datasets, the speed up for the bfs is 1.4x - 4x, for the pagerank 1.10x - 12x and in the other cases graphmat is actually slower than our sequential baseline. LCC doesn't even complete. The execution environment is a single machine, a dual Xeon(R) Gold 5115 CPU @ 2.40GHz, 10 cores per node, 40 physical threads in total in SMT, 386GB of RAM. 

At this point, we are wondering if our set up is correct. GraphMat is compiled as:

```mpic++ -cxx=g++ -fopenmp --std=c++11 -I/usr/include/mpi/ -I./include -I./include/GMDP -O3 -flto -fwhole-program -march=native -o bin/PageRank src/PageRank.cpp -lboost_serialization```

The compiler is actually icc:
```
# mpic++ -v
icpc version 19.0.0.117 (gcc version 9.2.0 compatibility)
```

The benchmark configuration is:
```
benchmark.custom.algorithms = BFS, CDLP, LCC, PR, SSSP, WCC
benchmark.custom.timeout = 3600
benchmark.custom.output-required = false
benchmark.custom.validation-required = false
benchmark.custom.repetitions = 7
```
Initially we set `benchmark.custom.output-required = true` but I think this only affects the makespan and not the processing time?

The platform properties are:
```
[Platform]
platform.name = Graphmat
platform.acronym = gmat
platform.version = ?
platform.link = ?
platform.graphmat.home = /export/scratch2/dleo/graphalytics/graphmat
platform.graphmat.intermediate-dir = /export/scratch2/dleo/temp
platform.graphmat.num-threads = 48
platform.graphmat.enable-slurm = False
platform.graphmat.num-machines = 1
platform.graphmat.command.prefix = env \
	I_MPI_DEBUG=2 I_MPI_FABRICS_LIST=tmi\,dapl\,tcp I_MPI_TMI_PROVIDER=psm2 \
	KMP_AFFINITY=scatter \
	OMP_NUM_THREADS=${platform.graphmat.num-threads} \
	salloc -N ${platform.graphmat.num-machines} --ntasks-per-node=1 \
	mpiexec.hydra numactl -i all
platform.graphmat.command.convert = ${platform.graphmat.command.prefix} %s %s
platform.graphmat.command.run = ${platform.graphmat.command.prefix} %s %s
platform.graphmat.hosts = localhost
#platform.graphmat.hosts = 10.149.0.1\,10.149.0.2
platform.graphmat.num_local_processes = 1
#platform.graphmat.num_local_processes = 2
platform.graphmat.command.prefix-no-slurm = env I_MPI_DEBUG=2 I_MPI_FABRICS_LIST=tmi\,dapl\,tcp I_MPI_TMI_PROVIDER=psm2\,KMP_AFFINITY=scatter\,OMP_NUM_THREADS=${platform.graphmat.num-threads} mpirun -np ${platform.graphmat.num_local_processes} --host ${platform.graphmat.hosts}
platform.graphmat.command.convert-no-slurm = ${platform.graphmat.command.prefix-no-slurm} %s %s
platform.graphmat.command.run-no-slurm = ${platform.graphmat.command.prefix-no-slurm} %s %s
```

Is there anything else we need to set up to optimise the running time of graphmat?

**Comment by mihaic** [comment]
The number of threads is probably too high. Try `platform.graphmat.num-threads = 20`.

**Comment by szarnyasg** [comment]
@whatsthecraic did you have any success reproducing the numbers? If so, I'd proceed to close this issue.

**Comment by whatsthecraic** [comment]
Hi Gabor, Mihai,
I tried decreasing the parallelism degree to 20 threads, with not much difference in the results.  The exception are the smallish graphs or some BFS, where actually the completion time worsened. Let me know if there is anything else to try, otherwise I`m happy to close the issue.
