### ISSUE TITLE
Clarification Needed: Platform Driver Graph Conversions

### ISSUE THREAD

**Issue by bashdash4** [ldbc/ldbc_graphalytics#194]
I am preparing to create a driver for a platform that strictly supports Matrix Market File format graphs, but I notice that Graphalytics' preferred format is .e and .v files for graphs. Is it expected that the platform itself will handle the conversion and/or processing of graphs, or can we make conversions through the driver via external scripts?

As well, are you aware of any conversion scripts that will convert graphs from .e and .v to .mtx and vice versa?

I appreciate any information that can be provided, thank you!

**Comment by amusaafir** [comment]
Hi,

You can run external graph conversion scripts through the driver of your platform. As a reference, you could have a look at the GraphMat driver which is essentially doing the [same thing](https://github.com/atlarge-research/graphalytics-platforms-graphmat/blob/7c8a01bfa06fb8325cebaf1f8c7acad9b653beb9/src/main/java/science/atlarge/graphalytics/graphmat/GraphmatPlatform.java#L82). Note that this is calling a binary which is compiled from the source code of the GraphMat platform itself.
The scripts you are looking for are not included in Graphalytics [utils](https://github.com/ldbc/ldbc_graphalytics/tree/master/bin/utils/graph-format-conversion) by default, but you could have a look at [GraphMat's conversion script](https://github.com/narayanan2004/GraphMat/blob/master/src/graph_converter.cpp) and perhaps even use the compiled version of this script directly.

**Comment by amusaafir** [comment]
You can also refer to the (more recent) [GraphBlas driver](https://github.com/FTSRG/ldbc-graphalytics-platform-graphblas) which also [includes a script](https://github.com/FTSRG/ldbc-graphalytics-platform-graphblas/blob/master/src/main/c/src/tools/converter.cpp) for the conversion.

**Comment by szarnyasg** [comment]
It seems this will be sorted out in https://github.com/gunrock/gunrock/issues/651.
Btw, is the issue title "Clarification Needed: Platform Driver Graph Conversions" still relevant?

**Comment by neoblizz** [comment]
We can close this issue now, will take care of this within the gunrock's issue repo. Thank you so much @szarnyasg again for all the pointers!

**Comment by szarnyasg** [comment]
Thanks for picking this up @neoblizz. I'm following the other issue.
