### ISSUE TITLE
Builds are broken due to missing license header template

### ISSUE THREAD

**Issue by szarnyasg** [ldbc/ldbc_graphalytics#208]
In many Graphalytics repositories, the build is broken as it checks the license header under https://graphalytics.org/assets/copyright-notice-template (which is currently a 404) using the `license-maven-plugin` Maven plugin:

https://github.com/ldbc/ldbc_graphalytics_platforms_reference/blob/17095e6fefe20fce8773b1c0881eb13e78eb7a5f/pom.xml#L134-L138

This check now fails due to the 404 issue.

**Comment by amusaafir** [comment]
I've uploaded the license — should work now.

**Comment by szarnyasg** [comment]
Thanks! I had to change `LICENSE` to `LICENSE.txt` and add the `NOTICE.txt` file but it indeed works now:
https://app.travis-ci.com/github/ldbc/ldbc_graphalytics_platforms_reference/builds/233346724

I'm keeping this issue open so that I'll fix it across all the repositories.
