### ISSUE TITLE
the certificate has expired

### ISSUE THREAD

**Issue by Eversee22** [ldbc/ldbc_graphalytics#210]
The certificate has expired. When I run `mvn clean package ` for graphx driver, I met the following probloem: 
`PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed: NotAfter: Tue Oct 26 20:00:00 CST 2021`
Could you please fix this.
Thank you!

**Comment by szarnyasg** [comment]
Hi @Eversee22, thanks for reporting this.
I created a mirror of the old Maven repository at https://ldbcouncil.org/graphalytics-mvn/ (served through GH Pages from https://github.com/ldbc/graphalytics-mvn).

I then:
- changed the URL in the GraphX project: https://github.com/atlarge-research/graphalytics-platforms-graphx/commit/a35d54b0577470db589f36694615ce158e88fa41
- nuked my locally cached Maven files
- and built the project

It worked! Let me know if this solves it for you as well.
