### ISSUE TITLE
Where can we find the cluster specifications of 2018 Spring competition?

### ISSUE THREAD

**Issue by parkerzf** [ldbc/ldbc_graphalytics#216]
May I ask where I could find the cluster specifications on your [website](https://graphalytics.org/competition)? It only shows the very high level configurations like `16 nodes, 32 threads `, while I am curious about the detailed settings such as:

* Which CPU?
* How big is the memory?
* What is the network bandwidth? 

Like what you put in this [document](https://graphalytics.org/assets/competition/2018_google_cloud_v_das5_graphalytics.pdf). 

Thank you very much!

**Comment by szarnyasg** [comment]
@parkerzf I was not involved with Graphalytics in Spring 2018 but I believe these experiments ran on the DAS-5 cluster.

**Comment by parkerzf** [comment]
Thanks!
