### ISSUE TITLE
Zeta and Geometric Generators

### ISSUE THREAD

**Issue by MarcoLotz** [ldbc/ldbc_graphalytics#97]
Hello,

in the paper, you mention the following:

"To support the ability to generate graphs of different characteristics, we have extended Datagen with the capability to dynamically reproduce different distributions by means of plugins. We have already implemented those for the Zeta and Geometric distribution models, but more will be added in the
future as more real graphs are analysed."

Where can I find the modified LDBC graph gens for Zeta and Geometric distributions?

**Comment by ArnauPrat** [comment]
Hi @MarcoLotz,
All the information regarding alternative ways to generate data is here:
https://github.com/ldbc/ldbc_snb_datagen/wiki/Advanced_Configuration
Please, do not hesitate to contact me if you need help.
Regards,
Arnau
